### ISSUE TITLE
link adress missed in readme

### ISSUE THREAD

**Issue by Siggi0904** [sapristi/mopidy-mowecl#2]
Hi,

how can I start these extension?
There is nothing written in readme.

All what I tried, I got a 404.

Thanks.

**Comment by sapristi** [comment]
Hello, after installing with pip,  it should be automatically started by mopidy, and accessible along with other mopidy web extensions.
What url did you try  ?
Also notice that the exact command to install with pip depends on the way mopidy was installed (as with other extensions).

**Comment by Siggi0904** [comment]
Hello,
I installed it via pip with the phrase from the mopidy extension site.
Your web client should be listed here: http://localhost:6680/mopidy/ but it isn't.

The link what I looked for is like the Mopidy-MusicBox-Webclient with a link like
http://localhost:6680/musicbox_webclient. What is the link to your mopidy web client?
I actually cannot check if it runs or what I have to do to connect.

Great thanks.

**Comment by sapristi** [comment]
Yes maybe I should do something about it, but this is really a mopidy/python issue. I think installing the extension with sudo should do the trick for you:
`sudo pip install mopidy-mowecl` 

The thing is that depending on the way mopidy is installed, it will only be aware of extensions installed with sudo (on debian).

**Comment by Siggi0904** [comment]
it is installed per sudo with sudo python3 -m pip install Mopidy-Mowecl
Looks the same like yours.

But it will not be shown.
What's the link in browser on localhost with mopidy to your web extension?
Which website link in browser you use?

**Comment by sapristi** [comment]
I use  `http://localhost:6680/mowecl/`, but if it's not shown in the list at `http://localhost:6680/mopidy/` I don't think it will work.

Do you know how you installed mopidy on your computer ?
You can also try to ask for help at https://discourse.mopidy.com/

**Comment by Siggi0904** [comment]
For installation I used the official way, see https://docs.mopidy.com/en/latest/installation/debian/
with http://192.168.178.24:6680/mowecl/ I get a 404 error.

**Comment by Siggi0904** [comment]
looks likeMowecl does not run.

`sudo mopidyctl deps
Running "/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf deps" as user mopidy
Executable: /usr/bin/mopidy
Platform: Linux-4.19.118+-armv6l-with-debian-10.4
Python: CPython 3.7.3 from /usr/lib/python3.7
Mopidy: 3.0.2 from /usr/lib/python3/dist-packages
Mopidy-MPD: 3.0.0 from /usr/local/lib/python3.7/dist-packages
  setuptools: 40.8.0 from /usr/lib/python3/dist-packages
  Pykka: 2.0.2 from /usr/lib/python3/dist-packages
  Mopidy: 3.0.2 from /usr/lib/python3/dist-packages
Mopidy-Local: 3.1.1 from /usr/local/lib/python3.7/dist-packages
  setuptools: 40.8.0 from /usr/lib/python3/dist-packages
  Pykka: 2.0.2 from /usr/lib/python3/dist-packages
  Mopidy: 3.0.2 from /usr/lib/python3/dist-packages
  uritools: 3.0.0 from /usr/local/lib/python3.7/dist-packages
Mopidy-MusicBox-Webclient: 3.1.0 from /usr/local/lib/python3.7/dist-packages
  setuptools: 40.8.0 from /usr/lib/python3/dist-packages
  Pykka: 2.0.2 from /usr/lib/python3/dist-packages
  Mopidy: 3.0.2 from /usr/lib/python3/dist-packages
GStreamer: 1.14.4.0 from /usr/lib/python3/dist-packages/gi
  Detailed information:
    Python wrapper: python-gi 3.30.4
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        id3demux
        id3v2mux
        lamemp3enc
        mpegaudioparse
        mpg123audiodec
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        flump3dec
        mad
`

**Comment by sapristi** [comment]
Ok it seems you are using mopidy as a service (`sudo mopidyctl ...`), and as as such mowecl should be installed with `sudo` as well.

Can you post the ouput of `sudo mopidyctl config` ?
The content of  `/var/log/mopidy/mopidy.log` could also help to debug.

**Comment by Siggi0904** [comment]
Oh, I don't know that this important. But yes, it is a service at  a headless raspbian
Needed files:
[mopidy.zip](https://github.com/sapristi/mopidy-mowecl/files/4793770/mopidy.zip)

**Comment by sapristi** [comment]
I think you should be good to go now :)

I forgot to say you needed to restart mopidy after installing a plugin. It seems that mowecl was finally enabled at your last restart today: 

```
Jun 17 17:45:11 music-pi mopidy[28446]: INFO     [MainThread] mopidy.__main__ Enabled extensions: musicbox_webclient, mowecl, softwaremixer, file, m3u, mpd, local, http, stream
Jun 17 17:45:11 music-pi mopidy[28446]: INFO     [MainThread] mopidy.__main__ Disabled extensions: none
Jun 17 17:45:13 music-pi mopidy[28446]: INFO     [MainThread] mopidy.commands Starting Mopidy mixer: SoftwareMixer
Jun 17 17:45:13 music-pi mopidy[28446]: INFO     [MainThread] mopidy.commands Starting Mopidy audio
Jun 17 17:45:13 music-pi mopidy[28446]: INFO     [MainThread] mopidy.commands Starting Mopidy backends: LocalBackend, FileBackend, M3UBackend, StreamBackend
Jun 17 17:45:14 music-pi mopidy[28446]: INFO     [Audio-2] mopidy.audio.actor Audio output set to "autoaudiosink"
Jun 17 17:45:14 music-pi mopidy[28446]: INFO     [MainThread] mopidy.commands Starting Mopidy core
Jun 17 17:45:14 music-pi mopidy[28446]: INFO     [MainThread] mopidy.commands Starting Mopidy frontends: MpdFrontend, HttpFrontend
Jun 17 17:45:14 music-pi mopidy[28446]: INFO     [MainThread] mopidy_mpd.actor MPD server running at [::ffff:0.0.0.0]:6600
Jun 17 17:45:14 music-pi mopidy[28446]: INFO     [HttpFrontend-10] mopidy.http.actor HTTP server running at [::ffff:0.0.0.0]:6680
Jun 17 17:45:14 music-pi mopidy[28446]: INFO     [MainThread] mopidy.commands Starting GLib mainloop
Jun 17 17:45:15 music-pi mopidy[28446]: INFO     [HttpServer] mopidy.internal.path Creating dir file:///var/lib/mopidy/mowecl
```

(you can also see that there is a `mowecl` section in the output of `mopidyctl config`, which means the extension is enabled)

**Comment by Siggi0904** [comment]
I restarted quite often, you see in log.

Hm, not so quite easy. The mowecl section in config was added manually by me.
Should be added to docs, same with the link  to the site: http://localhost:6680/mowecl/

Perhaps, the pip3 install command should be added to docs and Mopidy site too.

But finally, it runs magical. :-) Thanks.

**Comment by sapristi** [comment]
Well the config section is optional, extensions are enabled by default and there is no option to configure. 
The relevant part of extension installation for mopidy is at https://docs.mopidy.com/en/latest/installation/debian/#installing-extensions but I agree it is a bit of a mess to get it all sorted out.

The problem is that extension installation depends on the way mopidy was installed; all this is managed by the way packages are handled by python, which do not make it obvious where packages are installed (system wide or user only).

**Comment by sapristi** [comment]
@Siggi0904 Another reason things are complicated is that pip's behaviour is distro dependant, e.g. in archlinux, to install in userspace the command is `pip install package --user`, while it is only `pip install package` in debian.

**Comment by Siggi0904** [comment]
@sapristi For sure, it's quite difficult but list every command per each distro and users can select.

Actually it works perfectly but shirt questions.
How I can store changed colors permanently?
Is it translatable to german, perhabs with a online tool like Transifex?

How I can add aditional information's like artists, albums and genres in generell?
Actually all is empty in your web client.
Only local files from storage will be shown no ID3 tags.

**Comment by sapristi** [comment]
>  How I can store changed colors permanently?

After setting the colors in the settings panel, hitting the `commit` button will save the settings in your browse (this means that if you clear your browser data, the settings will be lost). I intend to provide a way to store setting on the mopidy server, but it is not ready yet.

>  Is it translatable to german, perhabs with a online tool like Transifex?

It is not translatable, and I do not really intend to make it so (if someone wants to do the job they are welcome :)

> Actually all is empty in your web client.
> Only local files from storage will be shown no ID3 tags.

Mowecl displays data sent by mopidy, it is not aware of id3 tags and such. What you want is the [Mopidy Local](https://mopidy.com/ext/local/) backend e.g.

**Comment by Siggi0904** [comment]
Okay, that's what did. Would be nice to have the an option to define it in configuration file permanently.
In my case, I delete my browser cache at the end of the day, and then I'll lost the configuration.

How much work is it to pipe the strings to a .po or .lang file for translation?
For around 30 strings should be easy to translate it offline and not with Transifex or other online tools.

Yes, I found the way to update the service mopidy at mopidy local for id3 tags.
They are not quite completely good, but it works.

Thanks for your work and for adding these features.

**Comment by sapristi** [comment]
> Okay, that's what did. Would be nice to have the an option to define it in configuration file permanently.
In my case, I delete my browser cache at the end of the day, and then I'll lost the configuration.

Ok I get that. What I first intended to do is to have a custom store server side to store the configuration. I'm aware this might be a bit overkill and have it in the configuration file might indeed achieve the same results and be much simpler for everyone. I'll think about that.

> How much work is it to pipe the strings to a .po or .lang file for translation?
> For around 30 strings should be easy to translate it offline and not with Transifex or other online tools.

Yes translation itself should be fairly easy, most of the work would be in integrating translated strings in the code. I have never done such a thing and have no idea what are the existing tools. In case that happens, I'd be much in favor of something light and simple.

**Comment by sapristi** [comment]
So I published a new version with possible configuration in the mopidy config file. I don't intend to provide translations anytime soon, as I have other plans right now.

**Comment by Siggi0904** [comment]
Sound's great.
In which way I can update?

can u add the url of your addon to the readme.
Then users know the command to open the Mowecl web interface.

Translation's are nice to have, it's ok.
What's your next plans?

**Comment by sapristi** [comment]
> Sound's great.
> In which way I can update?

`sudo pip3 install mopidy-mowecl --upgrade` should do the trick

>can u add the url of your addon to the readme.
> Then users know the command to open the Mowecl web interface.

Ok.

> What's your next plans? 

I would like to have a "Favorites" section (always on screen) for quick access to some items. 
I am also working on another extension that would move bookmarks functionality (autosave a tracklist + current track + current time for later resuming) server side.

**Comment by Siggi0904** [comment]
sudo pip3 install mopidy-mowecl --upgrade works fine, should be added to readme too, :-)

are the config items not added in default?
They are should. Or not?

Future plans sound great.

**Comment by sapristi** [comment]
> are the config items not added in default?
> They are should. Or not?

Default values for the extension parameters are provided in https://github.com/sapristi/mopidy-mowecl/blob/master/mopidy_mowecl/ext.conf, (used internally by mopidy) then it's up to the users to override them as they wish.
